version: '2'
services:
      app:
          build: .
          image: app:1.0.0
          volumes:
          - ./src://Users/mostafaguellil/Documents/GitHub/DevOps-Project
          ports:
          - "8080:80"